### ISSUE TITLE
Release candidate 2022-09-15

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1002]
New deployment including new versions of examples and setup.
* [aglais-notebooks v1.0.1](https://github.com/wfau/aglais-notebooks/releases/tag/v1.0.1)
* [gaiadmpsetup v0.1.4](https://github.com/wfau/gaiadmpsetup/releases/tag/v0.1.4)

**Comment by Zarquan** [comment]
Add a user account for Amy Krause; EPCC

**Comment by Zarquan** [comment]
Deployed on blue for acceptance testing.
http://blue.gaia-dmp.uk:8080

**Comment by Zarquan** [comment]
Latest examples run to completion.
(*) example 5 has memory errors and retries

**Comment by Zarquan** [comment]
Planning to make this version live Monday 3rd Oct.
TODO
* @Zarquan to publish a PR for the [branch](/Zarquan/gaia-dmp/tree/20220919-zrq-gardening)
* @Zarquan to send email to all users warning them system will be down Monday afternoon

**Comment by Zarquan** [comment]
Includes changes to copy the examples from [aglais-notebooks](https://github.com/wfau/aglais-notebooks/) - #999

**Comment by Zarquan** [comment]
Release delayed due to severe (50%) performance issues.
Performance is back up to normal now, so release is back on.

http://blue.aglais.uk:8080/#

**Comment by NigelHambly** [comment]
Done.
