### ISSUE TITLE
Release candidate  2022-09-27

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1016]
New deployment including :
* Permission to allow users to restart their interpreters #998
* Updates to the catalog schema in gaiadmpsetup #1009

**Comment by Zarquan** [comment]
Do we want to include additional Python libs
* 978

**Comment by Zarquan** [comment]
Test for row counts in full DR3 data:
User/NHambly/Full DR injests
check row count paragraph (needs to use local schema definition)

**Comment by NigelHambly** [comment]
User/NHambly/Full DR3 ingests. Note you'll need to extract the schema and function defs from the top of the notebook, and tweak the attach statements to point to the final resting place of the parquet files.

**Comment by Zarquan** [comment]
These are done, but leaving this open because we don't have tests to verify them yet.

**Comment by Zarquan** [comment]
I give up.
