### ISSUE TITLE
Remaining Gaia DR3 ingest items need transfer into official filesystem location

### ISSUE THREAD

**Issue by NigelHambly** [wfau/gaia-dmp#1018]
DR3 ingests are now complete which means the following are now available from /user/NHambly/PARQUET/GDR3/ to be staged on the official filesystem:

GDR3_ALERTS_MIXEDIN_SOURCEIDS
GDR3_EPOCH_PHOTOMETRY
GDR3_GALAXY_CANDIDATES
GDR3_GALAXY_CATALOGUE_NAME
GDR3_MCMC_SAMPLES_GSP_PHOT
GDR3_MCMC_SAMPLES_MSC
GDR3_NSS_ACCELERATION_ASTRO
GDR3_NSS_NON_LINEAR_SPECTRO
GDR3_NSS_TWO_BODY_ORBIT
GDR3_NSS_VIM_FL
GDR3_OA_NEURON_INFORMATION
GDR3_OA_NEURON_XP_SPECTRA
GDR3_QSO_CANDIDATES
GDR3_QSO_CATALOGUE_NAME
GDR3_SCIENCE_ALERTS
GDR3_SSO_OBSERVATION
GDR3_SSO_REFLECTANCE_SPECTRUM
GDR3_SSO_SOURCE
GDR3_TOTAL_GALACTIC_EXTINCTION_MAP
GDR3_TOTAL_GALACTIC_EXTINCTION_MAP_OPT
GDR3_VARI_AGN
GDR3_VARI_CEPHEID
GDR3_VARI_CLASSIFIER_CLASS_DEFINITION
GDR3_VARI_CLASSIFIER_DEFINITION
GDR3_VARI_CLASSIFIER_RESULT
GDR3_VARI_COMPACT_COMPANION
GDR3_VARI_ECLIPSING_BINARY
GDR3_VARI_EPOCH_RADIAL_VELOCITY
GDR3_VARI_LONG_PERIOD_VARIABLE
GDR3_VARI_MICROLENSING
GDR3_VARI_MS_OSCILLATOR
GDR3_VARI_PLANETARY_TRANSIT
GDR3_VARI_RAD_VEL_STATISTICS
GDR3_VARI_ROTATION_MODULATION
GDR3_VARI_RRLYRAE
GDR3_VARI_SHORT_TIMESCALE
GDR3_VARI_SUMMARY

**Comment by Zarquan** [comment]
Work in progress .. blocked by an issue with the Arcus platform (see #1050).
