### ISSUE TITLE
Saving results

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1025]
Support request from SGoughKelly :
> Saving figures:
> The examples do show how we can plot effectively within pyspark but I have been having issues with saving figures to my user area in order to transfer them off DMP. Can you show an example of this how to do it correctly. It seems the python interpreter can save figures to the home area but that would mean having to transfer results between pyspark and python interpreters.
> 
> File Permissions from Pyspark save files.
> So following through the example sent to me via email:
> 
>     %pyspark
>     # Write the results to disc ..
>     df.write.save(
>       "file:///user/SGoughKelly/my-first-results"
>       )
> 
> The results of a query got saved in the correct place as follows :
> 
>     drwxr-xr-x.  2 fedora      fedora             402 Aug  2 00:26 my-first-results
> 
> Which means I dont own the directory where these results are saved, so I cannot remove them. This was just a test so would be good to remove and it is impractical to log a request every time I’d need something like this removed. Is there are way to fix this so I can remove it myself or did I make an error in saving this result.

**Comment by Zarquan** [comment]
Duplicate of #1024, apologies.

**Comment by NigelHambly** [comment]
I'll close this one then; the earlier one is assigned to me and I'll look in to it.
