### ISSUE TITLE
Configurable data location

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1053]
Modify the `gaiadmpsetup` library to support a configurable location, `GAIA_DATA_LOCATION` for the Gaia data.

The default settings would continue to use the data from the CephFS shares.

> %pyspark
> import gaiadmpsetup

Setting the `GAIA_DATA_LOCATION` provides a different location.

> %pyspark
> GAIA_DATA_LOCATION=hdfs://master01:9000/data/GAIA_DR3
> import gaiadmpsetup

**Comment by Zarquan** [comment]
Ideally we should be able to swap between posix file system, `file://....`, Hadoop filesystem, `hdfs://....` and S3 cloud data, `s3://....`, within the same notebook or in different notebooks.

This will make it much easier to measure benchmarks for different filesystems and different platforms.

**Comment by stvoutsin** [comment]
Fixed by @akrause2014  and included in PR: https://github.com/wfau/gaia-dmp/pull/1154
