### ISSUE TITLE
Front page stalling or failing to load

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1057]
Reports of the front page stalling or failing to load.

Nigel Hambly 17:37 22 November 2022 
> I’ve had reports, and noticed occasionally, that the URL https://dmp.gaia.ac.uk/ presents a blank page on first navigating to it. Sometimes pressing refresh in the browser makes the Zeppelin UI home login page appear; sometimes several presses and a short wait are necessary. Is the UI all ok and healthy?
>
> I got Eckhard to check in Chromium/CentOS and it works first time for him, having never accessed the service before. (I use Safari on MacOS btw). Eckhard pointed out that the home page URL looks a bit funny in the navigation bar, e.g. something like
>
> https://dmp.gaia.ac.uk/#/?%20
>

**Comment by Zarquan** [comment]
Not seen this myself. I'll have a think about how to replicate it.

I know what you mean about the 'odd' URL, but I think it is a side effect of the JavaScript toolkit Zeppelin use to create the page.

**Comment by Zarquan** [comment]
Email from N.Walton 23 Nov
> btw - when i use Safari Version 16.1 (18614.2.9.1.12) on a Macosx ventura 13.0.1 - i get a blank screen at  https://dmp.gaia.ac.uk/. 
> however, i get the zeppelin screen when i use Chrome Version 107.0.5304.110 (Official Build) (arm64) - and i can login ok from there.

**Comment by NigelHambly** [comment]
I can sometimes replicate the problem if I logout from Zeppelin and close the tab in my browser... but not always!

BTW the logout button is very sluggish atm: I press it, and have to wait some 10s of seconds before the operation is acknowledged in the browser window as "logout success"... then the window goes blank for a bit before the Zeppelin login homepage appears! Maybe it's all related: seems that something somewhere is asleep and needs to be woken up by multiple operation requests actioned by browser buttons, or alternatively a significant wait ...? 

The impression I get that if I wait long enough all operations are actioned, so maybe it's something on the front-end that is simply being sluggish (is there an Apache Tomcat, or equivalent, in the layers somewhere that needs a kick?).

**Comment by Zarquan** [comment]
For now, we should all just keep an eye on this and log anything of interest.
* When it is slow, and when it is fast.
* Where you are accessing the site from (home, work etc.) and whether you are using a VPN. 
* How many other tabs open in the browser at the time (lots, some, few, none)
* How long since the browser was started from clean (now, this hour, today, this week)

Also, could everyone visit this link https://www.whatsmybrowser.org/ and copy/paste the URL it generates into an email and send it to <gaiadmp-support@roe.ac.uk>.

**Comment by stvoutsin** [comment]
I think I've identified the cause, which is that Zeppelin redirects to an http://../api/login  address (not https). This causes security errors in all browser that I've seen, but Safari time's out the request. I'm looking into possible fixes, will update with more info here

For context this is the error in Chrome:
`Mixed Content: The page at 'https://dmp.gaia.ac.uk/#/?ref=%2F' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dmp.gaia.ac.uk/api/login'. This request has been blocked; the content must be served over HTTPS.`

**Comment by NigelHambly** [comment]
Good catch!

**Comment by Zarquan** [comment]
Can we reproduce the redirect sequence using `curl` ? If so, then we should be able to create a shell script that verifies that this is fixed.

**Comment by stvoutsin** [comment]
This has been resolved and tested with the most recent deploy by Nigel, so setting this to closed. Not sure how to recreate the issue with curl as it's a Safari specific problem, but if we want to set that as a target shall we create a new issue for it?

**Comment by Zarquan** [comment]
> .. shall we create a new issue ?

Either keep this one open or create a new issue for the test. Simply closing this issue without creating something for the test means this will never get tested. 

> Not sure how to recreate the issue with curl as it's a Safari specific problem

What changed in the new deployment that fixed the issue ?

Based on your diagnosis:
> I think I've identified the cause, which is that Zeppelin redirects to an http://../api/login address (not https). This causes security errors in all browser that I've seen, but Safari time's out the request. I'm looking into possible fixes, will update with more info here

The problem wasn't Safari specific, it was our service redirecting to the wrong location. It showed up in Safari, because they have stricter security checks, but the cause was a bad redirect coming from our service.

In which case, we should be able to create a script that uses curl to check it redirects to the right location by checking the HTTP header fields. See [#1089 comment-1400734410](https://github.com/wfau/gaia-dmp/issues/1089#issuecomment-1400734410)
