### ISSUE TITLE
Error during deploy, getaddrinfo data.aglais.uk fails

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1064]
**Error log:**

TASK [Accept SSH key for data node] ********************************************
fatal: [zeppelin]: FAILED! => {"changed": true, "cmd": "ssh-keyscan 'data.aglais.uk' >> \"${HOME}/.ssh/known_hosts\"\n", "delta": "0:00:00.025871", "end": "2022-11-29 20:00:04.392263", "msg": "non-zero return code", "rc": 1, "start": "2022-11-29 20:00:04.366392", "stderr": "getaddrinfo data.aglais.uk: Name or service not known\r\ngetaddrinfo data.aglais.uk: Name or service not known\r\ngetaddrinfo data.aglais.uk: Name or service not known", "stderr_lines": ["getaddrinfo data.aglais.uk: Name or service not known", "getaddrinfo data.aglais.uk: Name or service not known", "getaddrinfo data.aglais.uk: Name or service not known"], "stdout": "", "stdout_lines": []}

At a first glance, under the known hosts I see a key for "data.gaia-dmp.uk", but not for "data.aglais.uk"

See:
https://github.com/wfau/gaia-dmp/blob/master/deployments/hadoop-yarn/ansible/39-create-user-scripts.yml#L253

Perhaps data.aglais.uk needs to be changed in the 39-create-user-scripts.yml script?

**Comment by Zarquan** [comment]
yep, see #996

**Comment by Zarquan** [comment]
This is fixed in the branch that I'm currently working on. So make a temp fix to get your deployment to work but don't commit the change.
Apologies - my branch has been out for too long.

**Comment by stvoutsin** [comment]
Okay sounds good, I've applied a temp fix and this is what I'm testing with
