### ISSUE TITLE
Errors with Ceph shares (deleting fail) & Object store in Arcus (view / create fail)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1078]
**Issue 1**
When running the deployment script, the deletion of the Ceph shares fails with the following error messages:

```

Failed to delete share with name or ID 'iris-gaia-red-home-Drizzbinson': Invalid share: Share status must be one of ('available', 'error', 'inactive'). (HTTP 403) (Request-ID: req-31e5f351-a726-4bb5-a7d8-ef77b852361f)
...
Failed to delete share with name or ID 'iris-gaia-red-user-Drizzbinson': Invalid share: Share status must be one of ('available', 'error', 'inactive'). (HTTP 403) (Request-ID: req-c7828ae8-ab94-456e-85e8-d15775465153)
```

The shares also appear to be stuck in a "Deleting" status in the Horizon Dashboard.

**Issue 2**

Unable to view / create Object storage containers from the Horizon Dashboard. As soon as I navigate to the Object Storage - Containers page,  i get logged out automatically. The error messages that appear briefly on the top right:

`Unauthorized. Redirecting to login`

`Unable to get the Swift container listing.`

**Comment by Zarquan** [comment]
I think this is 2 separate issues.

**Comment by Zarquan** [comment]
For the Manila shares - the both have the same name. Can you include the long UUID identifters of the stuck shares.

**Comment by Zarquan** [comment]
For the object storage, can you try using the command line and see if we can get a more detailed error message ?

**Comment by stvoutsin** [comment]
> For the Manila shares - the both have the same name. Can you include the long UUID identifters of the stuck shares.

Here's the list of UUIDs for the stuck shares:

f8c7504b-dda0-4124-be2e-043bc4584c21
f5c80f34-3506-4a3e-aae5-50c969085519
409edc3a-39b9-48ca-9ee7-1f6f57b0aff3
606334d3-9e85-41a0-94d3-3a9d1e308af9
31fef0ee-b97f-4d5b-bf35-427be3083ea1
f8e177e8-81f9-4b5b-9b88-cdfff94c295f
5f4c54e4-efb4-401f-8e58-2dbd61de72d2
f66b235f-a0f9-482c-b51d-a9fbcb237e9d
10ded69d-24b7-44dc-84ff-32d182a733f8
d3a2e89a-2c34-4642-bf2d-ea2241da3357
fa4e234a-76e0-4b01-a9b2-a729fcf9193d
f3280ee7-87b2-4f7d-b4e7-e9c1b5fc05ae
3cd734e0-f795-45b6-bcfc-603a1d23f70a
cb52385e-5b7d-4cd0-abf4-6aa29a0c1a38
a840db73-bd73-4a54-ae67-7817af362c66
340b21fe-6b57-4f7a-98c6-192bd47c09c2
ed45721d-c442-4937-a838-321b611aeeaa
68947e76-7367-4469-83e9-5809ac66d464
4a5e0d8a-8780-4f71-9cce-7322b829b56c
94ea1093-54fe-4904-94c4-332dbcc46241

**Comment by Zarquan** [comment]
These look like separate issues
* #1079
* #1080
