### ISSUE TITLE
Object store in Arcus (view / create fail)

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1080]
From issue logged by @stvoutsin #1078 

> Unable to view / create Object storage containers from the Horizon Dashboard. As soon as I navigate to the Object Storage - Containers page,  i get logged out automatically. The error messages that appear briefly on the top right:
```
`Unauthorized. Redirecting to login`

`Unable to get the Swift container listing.`
```

> Running _swift list_ in the Ansibler container produces the following error:
```
Account GET failed: https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_......?format=json 401 Unauthorized  [first 60 chars of response] b'{"Code":"AccessDenied","RequestId":"tx00000000000000004d351-'
Failed Transaction ID: tx00000000000000004d351-006...
```

**Comment by stvoutsin** [comment]
Issue seems to be solved now, listing and creating in Object store works as of yesterday
