### ISSUE TITLE
Service offline page

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1086]
We need to have a page that says _"The Gaia DMp service is offline for maintenance"_ that we can put in place of the live service to deflect users while we repair a broken system.

This could be implemented as a simple HTML page with the Gaia-DMp branding installed on the Nginx proxy.

To block access we re-direct requests for the live site domain to the static page, leaving the `iris-gaia-{colour}.gaia-dmp.uk` domain name access in place.

That would prevent external users from accessing the site, but it would allow us to use the `iris-gaia-{colour}.gaia-dmp.uk` domain name for debugging and testing.

**Comment by Zarquan** [comment]
Split this into two stages.
* The technical part of implementing the HTML page, deploying it using Ansible and integrating it with the Nginx config.
* Adding a nice branding to match our updated Zeppelin UI

**Comment by Zarquan** [comment]
Might also need to consider having an alternative platform for just this one page. So that if the entire Openstack system is down, we can point our DNS record to an alternative location.

This is not as far out as it may sound. We have been given notice that Cambridge will be doing maintenance work on the network for the Arcus Openstack platform on the 14th Feb. We can put this page up on the existing deployment, but that relies on at least part of the Openstack platform working to be able to serve the page.

We might want serve the page on a minimal VM on another platform while the Openstack platform is down. Quickest would be to use Linode or DigitalOcean. The cost of a tiny VM for one day is minimal, compared to the administrative hassle of running a VM on one of the other Openstack platforms.

**Comment by stvoutsin** [comment]
I've created a Service offline page that should now be included in the Ansible scripts and any new deployment. Notes on how to use it can be found here:
https://github.com/wfau/gaia-dmp/pull/1161/files
If this is sufficient for this task feel free to close it.
