### ISSUE TITLE
Certificate renewal failing on live

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1088]
Error message includes following message:

>    http://dmp.gaia.ac.uk/.well-known/acme-challenge/i-ympkgHi....:
>    Timeout during connect (likely firewall problem)
> 
>    To fix these errors, please make sure that your domain name was
>    entered correctly and the DNS A/AAAA record(s) for that domain
>    contain(s) the right IP address. Additionally, please check that
>    your computer has a publicly routable IP address and that no
>    firewalls are preventing the server from communicating with the
>    client. If you're using the webroot plugin, you should also verify
>    that you are serving files from the webroot path you provided.
> 

Note the URL is an http:// one, and we no longer have port 80 open

It looks like we do need port 80 open for the validation needed during Let's encrypt renewal process (Unless there are other alternatives that I'm missing)
https://community.letsencrypt.org/t/timeout-during-connect-likely-firewall-problem/80101/8

**Comment by Zarquan** [comment]
Makes sense - you can't use an expired certificate to renew a certificate. 

Probably just for one specific location though, so we can have a http=>https redirect for everything apart from this specific location.

**Comment by stvoutsin** [comment]
I think as far as I know we still have to have port 80 open even if we are redirecting everything to https. If we block port 80, I think accessing http://dmp.gaia.ac.uk will not resolve at all. After opening port 80 the renewal process works fine (note that the certificate hadn't yet expired, it was expiring in a few days)

**Comment by Zarquan** [comment]
Can we run some tests to check what happens on port 80 ?

**Comment by Zarquan** [comment]
See #1089
