### ISSUE TITLE
Combine new schema with new data

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1090]
Combine the new data from #1018 with the updated schema in https://github.com/wfau/gaiadmpsetup/pull/12

Steps
1. Setup test deploy using gaiadmpsetup branch and new Ceph share mounted
1.1 Mount CephFS share with full DR3 data
1.1 Edit Python `requirements.txt` to refer to specific branch in gaiadmpsetup
2. Test new data with notebooks
3. Complete PR gaiadmpsetup 12 to create new release of gaiadmpsetup
4. Update live gaia-dmp to use new release of gaiadmpsetup

**Comment by NigelHambly** [comment]
Looks OK to me. I executed the following on blue (right?):

`import gaiadmpsetup`
`import numpy as np`

`spark.sql("USE gaiadr3")`
`tables_df = spark.sql("SHOW TABLES")`
`tables_array = np.array(tables_df.select('tableName').collect()).reshape(-1)`

`for table in tables_array: `
`    print('\n\n\n')`
`    print(table + " row count: " + str(spark.sql("select count(*) from " + table).collect()[0]))`
`    spark.sql("select * from " + table).show()`

... and the row counts look correct, plus the data in the first 20 rows of each.

**Comment by Zarquan** [comment]
I've created a new release on `gaiadmpsetup`, called it version 1.0.0 because this is the first full schema for DR3.
https://github.com/wfau/gaiadmpsetup/releases/tag/v1.0.0

Next step will be to include it in a new deployment of `gaia-dmp` and make it live #1127.

**Comment by Zarquan** [comment]
This step is done, the next step is #1127
