### ISSUE TITLE
Tests to check unused ports are not left open

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1098]
Due to limitations of the HTTPS configuration we need to open port 8080 and allow clear text HTTP access to be able to roun external tests on a deployment.

We don't close port 8080 afterwards.

We need a test that checks that only a specific set of allowed ports are left open.

**Comment by stvoutsin** [comment]
With the latest changes we shouldn't be opening port 8080 anymore, so this should be fixed
Test included in https://github.com/wfau/gaia-dmp/pull/1151
