### ISSUE TITLE
Deployment sequence needs to close port 8080

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1099]
Due to limitations of the HTTPS configuration we need to open port 8080 and allow clear text HTTP access to be able to roun external tests on a deployment.

We don't close port 8080 afterwards.

The live service is left with an open HTTP port.
https://github.com/wfau/gaia-dmp/issues/1098

**Comment by stvoutsin** [comment]
One thing I've been doing for my test deploys, is starting nginx and just running the tests on port 80 in which case we don't have to open port 8080 for tests. In any case was this issue specific to the recent deploy on red, if so shall we close it?

**Comment by Zarquan** [comment]
Until we have HTTPS on all the colors, #838, we need to make sure that whatever we do to open the system up for testing never gets left open. Bad operators are continually be port scanning for known vulnerabilities.

Possibly combine this with #1089, so the deployment process always runs a test to check that the correct redirects are in place and there are no known vulnerabilities.

**Comment by Zarquan** [comment]
This is only necessary while we continue to use port 8080 for testing. Once we fix the SSL certificates (#838) this will no longer be an issue.

**Comment by stvoutsin** [comment]
This should now be fixed
