### ISSUE TITLE
testall script not completing in most recent deployment

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1103]
**Description:**

testall script from (/deployments/zeppelin/bin/zeppelin-rest-tools.sh) did not complete in most recent deploy

https://github.com/wfau/gaia-dmp/blob/b72285319a72b7a631ff26bd136c8567946ce713/notes/stv/20230125-red-deploy-01.txt#L267
     
Need to do test out on a new deploy to confirm whether this is an issue, and if so what it is.

**Comment by Zarquan** [comment]
If the same deployment passes the same test a second time, leave this issue open but don't spend too long on debugging it. If we don't see it happening again in future deployments we can close this. If it happens again we have a marker to refer to when it first started happening.
