### ISSUE TITLE
Wrong hostname in recent deploy / SSL installation playbook fails

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1106]
In the most recent deploy on red (https://github.com/wfau/gaia-dmp/blob/b72285319a72b7a631ff26bd136c8567946ce713/notes/stv/20230125-red-deploy-01.txt)
the hostname variable was set to zeppelin.gaia-dmp.uk, which made the SSL installation step fail, as the certificate uses the dmp.gaia.ac.uk name, which didn't match the hostname created in the NGINX server config.

Need to either sort out why this happened, and find either a short term fix, or wait till the SSL installation is refactored, where this may no longer be relevant

**Comment by Zarquan** [comment]
I think this has always been a manual step. I copied this section from your notes for my deployments.
https://github.com/wfau/gaia-dmp/blob/8b442c345ae0fce2749baecbdd9f13e696a88aff/notes/stv/20220728-Setup-SSL.txt#L49-L65

**Comment by Zarquan** [comment]
This will be fixed when we fix the SSL certificates #838

**Comment by stvoutsin** [comment]
This should now be fixed with https://github.com/wfau/gaia-dmp/issues/838 closed
