### ISSUE TITLE
Unable to allocate IP addresses on Arcus

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1128]
**Description**

Ansible deployment on green fails with the following message:
`
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": null, "details": "No more IP addresses available on network 57add367-d205-4030-a929-d75617a7c63e.", "response": "{\"NeutronError\": {\"type\": \"IpAddressGenerationFailure\", \"message\": \"No more IP addresses available on network 57add367-d205-4030-a929-d75617a7c63e.\", \"detail\": \"\"}}"}, "msg": "ConflictException: 409: Client Error for url: https://arcus.openstack.hpc.cam.ac.uk:9696/v2.0/floatingips, No more IP addresses available on network 57add367-d205-4030-a929-d75617a7c63e."}`

**Comment by Zarquan** [comment]
What does the list-all script show for the three clouds ?
https://github.com/wfau/gaia-dmp/blob/master/deployments/openstack/bin/list-all.sh

**Comment by stvoutsin** [comment]
> What does the list-all script show for the three clouds ? https://github.com/wfau/gaia-dmp/blob/master/deployments/openstack/bin/list-all.sh

In terms of floating IP addresses, the script shows 1 floating IP address for red, 1 for blue and none for green

**Comment by Zarquan** [comment]
OK, so we aren't over quota then.

When it lists the networks, can you check to see if `57add367-d205-4030-a929-d75617a7c63e` is the internal network created by our scripts, or is it the public external one ?

**Comment by stvoutsin** [comment]
It looks like its using the internal network (`a56320be-459a-41f5-83db-ecb6502f3300`)

**Comment by Zarquan** [comment]
I've posted a comment on the Slack channel, will see what Paul says.

**Comment by stvoutsin** [comment]
Actually I may have missread, the network list for green lists both an internal and the "CUDN-Internet" networks:

**Comment by stvoutsin** [comment]
I've also tried creating a Floating IP address from the Horizon Dashboard (using CUDN-Internet Network) and get the same error ("Unable to Allocate Floating IP")

**Comment by stvoutsin** [comment]
Closing this, as it seems that the issue has been fixed from the Arcus side
