### ISSUE TITLE
Fix benchmark tests to use the right version of test notebooks

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1138]
A recent pull request dropped the expected time for the spectra search notebook from 1800s to 15s, because the test is referring to the wrong version of the notebook.

https://github.com/wfau/gaia-dmp/pull/1130/files#diff-e1e2d340910fd220d8a71ab0b87f44e0196083335b131a9f9bdaf4921ce645bfL33-L38

We need to review all of the benchmark tests to check that they are using the right version of the notebooks.

**Comment by Zarquan** [comment]
Linking this to #1139 so that we can verify that the right version has been executed.

**Comment by Zarquan** [comment]
Note the benchmark config file doesn't reference a specific version of the test notebooks, so the version executed will depend on what is in main/master at the point where the tests are run.

100% not reproducible, so the execution time cannot be compared to previous runs.

We need to refer to a specific release version of the test notebooks

**Comment by Zarquan** [comment]
An unexpected drop from `1800` seconds to `15` seconds should probably not be considered a PASS.
We probably need a max and min value for the execution times so that unexpected changes are flagged as FAIL.

**Comment by stvoutsin** [comment]
Fixed in: https://github.com/wfau/gaia-dmp/pull/1152
Re-open if you disagree that this is completed
