### ISSUE TITLE
Benchmark testing for Cambridge workshop

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#1145]
Verify that we can run a loop of concurrent tests with the expected number of users. 

Create a report that details how responsive the system is for an individual user running through the examples.
Including how long each example takes to start and how long each example takes to complete.

Test different configurations :
* A single deployment for the whole workshop.
* Three smaller deployments each handling a third of the load.

**Comment by Zarquan** [comment]
Create a report that details how responsive the system is for an individual user running through the examples.

**Comment by Zarquan** [comment]
How long each example takes to start and how long each example takes to complete.

**Comment by NigelHambly** [comment]
As discussed last week:

- my strong preference is that whatever we do, we do not disturb the live system in any benchmarking
- also there is no need to make a huge, open-ended investigation: let's keep things focused on demonstrating to ourselves that we can handle a reasonable workshop scenario

To that end my suggestion is as follows:

- redeploy the two offline two-thirds of our resource as a single workshop benchmark deployment
- target a level of max 12 concurrent users
- reconfigure such that (say) up to half that number have immediate access to spark cluster resources, i.e. up to 6 users won't see cells pending at any one time
- make sure we can control Zeppelin UI, individual interpreters and the Spark cluster (e.g. via the Spark UI) in the case that individual users lock up their own session, or any shared resource, that is to say ensure that individuals cannot bring the entire workshop to a standstill, either by mistake or deliberately (!)

**Comment by Zarquan** [comment]
We are not doing a workshop at the Cambridge meeting, so this is probably getting dropped ?
See #1144

**Comment by NigelHambly** [comment]
Yep

**Comment by Zarquan** [comment]
Still need to do the testing, but that isn't popular at the moment.
