### ISSUE TITLE
Upgrade user-create scripts to clone newer notebook release

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1163]
New release version is v1.0.2
NOTE: Newer version also adds a new directory "ipynb". This is meant just for the github repository, but we don't want it appearing under the Zeppelin user directory so we'll have to delete that.
Also may have to change the scripts to accommodate for the changes to the Notebook names, which no longer have the suffix.

**Comment by Zarquan** [comment]
Is this done ?
We have moved on to v1.0.3 of the notebooks, but have the additional steps been completed ?

**Comment by stvoutsin** [comment]
I've verified that we've moved to v1.0.3 and that we don't copy over the ipynb folder, so I'll set this issue as done
