### ISSUE TITLE
Issue with Arcus cloud / Slow queries

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#1216]
We've seen a number of issues this week on the production & test deployments, which may or may not be related. I'll list what I've found here to see if we can debug this, or report to Cambridge:

- Test deploy on blue fails to import test users:
  
The test script creates the first user "Reyesfan", then gets stuck at the second user:

>     "debug": {
>                 "script": "create-ceph-share.sh",
>                 "result": "PASS",
>                 "messages": ["PASS: Share [iris-gaia-blue-user-Evison][25c7cb0d-035d-43e1-adef-767dbbd835df] status [available]","PASS: Ansible mount playbook succeded"]
>                 }
>             }
>             ,
>             "linuxuser": 
>         
> 

Shares are created and are visible in Openstack

- Test deploy on blue fails to run Source counts notebook:

Plot up the results cell does not complete, (Has been running for 30 mins)
Note: "Start here" notebook ran successfully 

Noting what we see in the Spark UI after 30 mins: 308/4979 (70 running)
No unhealthy nodes, all seem to be available, and application is using >90% of cluster.

- Queries on production server not completing
Noted by Nigel, reproduced by @stvoutsin

**Comment by stvoutsin** [comment]
Update: I ran the import users test script after removing the "Evison" user from the list and it completed this time.

**Comment by stvoutsin** [comment]
I stopped the above job, and started a simple pi calculation:
https://raw.githubusercontent.com/stvoutsin/aglais-testing/main/notebooks/pi_calculation.json
(Reduced samples to 20000)

**Comment by stvoutsin** [comment]
Running this in python just hangs:

```
import pandas as pd
parquet_file_path = '/data/gaia/GDR3/GDR3_GAIASOURCE/part-01047-18ac60bc-42ce-42dd-ab5b-fc0027a56a2c_01047.c000.snappy.parquet'
df = pd.read_parquet(parquet_file_path)
```

**Comment by stvoutsin** [comment]
Checking the CephFS mounts on each machine.
[root@ansibler]

    machines=(
        zeppelin
        worker01
        worker02
        worker03
        master01
        )

    for machine in "${machines[@]}"
    do
        echo
        echo "Machine [${machine}]"

        ssh "${machine}" \
            '
            date
            hostname
            for mountpoint in $(
                cat /etc/fstab | sed -n "/ceph/ p" | cut -d " " -f 2
                )
            do
                echo "Mount [${mountpoint}]"
                sudo du -d 1 -h "${mountpoint}"
            done
            '
    done

    
    ..

>     Machine [worker01]
> Fri Sep 22 13:54:27 UTC 2023
> iris-gaia-blue-20230922-worker01
> Mount [/data/gaia/GEDR3]
> 163G	/data/gaia/GEDR3/GEDR3_2048_PS1_BEST_NEIGHBOURS
> 60G	/data/gaia/GEDR3/GEDR3_2048_2MASSPSC_BEST_NEIGHBOURS
> 561G	/data/gaia/GEDR3/GEDR3_2048_GAIASOURCE
> 177G	/data/gaia/GEDR3/GEDR3_2048_ALLWISE_BEST_NEIGHBOURS
> 959G	/data/gaia/GEDR3
> Mount [/data/gaia/GDR3]
> 

Zeppelin and master01 mounts are fine, but reading GDR3 on all the workers hangs..

**Comment by stvoutsin** [comment]
I tried unmounting / remounting, and it just hangs:
```

machines=(
            worker01
            worker02
            worker03
            )

        for machine in "${machines[@]}"
        do
            echo
            echo "Machine [${machine}]"
            ssh "${machine}" \
                '
                date
                hostname
                echo
                for mountpoint in $(
                    cat /etc/fstab | sed -n "/ceph/ p" | cut -d " " -f 2
                    )
                do
                    echo "Mount [${mountpoint}]"
                    sudo umount "${mountpoint}"
                    sudo mount  "${mountpoint}"
                done
                '
        done

```
Machine [worker01]
Fri Sep 22 14:00:18 UTC 2023
iris-gaia-blue-20230922-worker01

Mount [/data/gaia/GEDR3]
..

**Comment by stvoutsin** [comment]
journactl messages on worker01 (blue test deploy):

> 
> Sep 22 12:10:39 iris-gaia-blue-20230922-worker01 kernel: libceph: mon3 (1)10.4.200.25:6789 session established
> Sep 22 12:10:39 iris-gaia-blue-20230922-worker01 kernel: libceph: client281110280 fsid a900cf30-f8a3-42bf-98d6-af7ce92f1a1a
> Sep 22 12:18:34 iris-gaia-blue-20230922-worker01 kernel: libceph: mon3 (1)10.4.200.25:6789 session established
> Sep 22 12:18:34 iris-gaia-blue-20230922-worker01 kernel: libceph: mon3 (1)10.4.200.25:6789 socket closed (con state OPEN)
> Sep 22 12:18:34 iris-gaia-blue-20230922-worker01 kernel: libceph: mon3 (1)10.4.200.25:6789 session lost, hunting for new mon
> Sep 22 12:18:34 iris-gaia-blue-20230922-worker01 kernel: libceph: mon4 (1)10.4.200.26:6789 session established
> Sep 22 12:18:34 iris-gaia-blue-20230922-worker01 kernel: libceph: client268532428 fsid a900cf30-f8a3-42bf-98d6-af7ce92f1a1a
> Sep 22 12:19:37 iris-gaia-blue-20230922-worker01 kernel: libceph: mon2 (1)10.4.200.17:6789 session established
> Sep 22 12:19:37 iris-gaia-blue-20230922-worker01 kernel: libceph: mon2 (1)10.4.200.17:6789 socket closed (con state OPEN)
> Sep 22 12:19:37 iris-gaia-blue-20230922-worker01 kernel: libceph: mon2 (1)10.4.200.17:6789 session lost, hunting for new mon
> Sep 22 12:19:37 iris-gaia-blue-20230922-worker01 kernel: libceph: mon1 (1)10.4.200.13:6789 session established
> Sep 22 12:19:37 iris-gaia-blue-20230922-worker01 kernel: libceph: client281060132 fsid a900cf30-f8a3-42bf-98d6-af7ce92f1a1a
> Sep 22 12:35:10 iris-gaia-blue-20230922-worker01 kernel: libceph: osd680 (1)10.4.200.112:6813 socket closed (con state CONNECTING)
> Sep 22 12:35:10 iris-gaia-blue-20230922-worker01 kernel: libceph: osd686 (1)10.4.200.112:6837 socket closed (con state CONNECTING)
> Sep 22 12:35:10 iris-gaia-blue-20230922-worker01 kernel: libceph: osd703 (1)10.4.200.118:6849 socket closed (con state CONNECTING)
> Sep 22 12:35:10 iris-gaia-blue-20230922-worker01 kernel: libceph: osd672 (1)10.4.200.106:6837 socket closed (con state CONNECTING)
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd698 (1)10.4.200.118:6829 socket error on read
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd694 (1)10.4.200.118:6813 socket closed (con state CONNECTING)
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd684 (1)10.4.200.112:6829 socket closed (con state CONNECTING)
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd702 (1)10.4.200.118:6845 socket error on write
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd665 (1)10.4.200.106:6809 socket closed (con state CONNECTING)
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd695 (1)10.4.200.118:6817 socket error on write
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd139 (1)10.4.200.106:6801 socket error on read
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd667 (1)10.4.200.106:6817 socket error on write
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd689 (1)10.4.200.112:6849 socket error on write
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd677 (1)10.4.200.112:6801 socket closed (con state CONNECTING)
> Sep 22 12:35:14 iris-gaia-blue-20230922-worker01 kernel: libceph: osd699 (1)10.4.200.118:6833 socket closed (con state CONNECTING)
> Sep 22 12:35:18 iris-gaia-blue-20230922-worker01 kernel: libceph: osd676 (1)10.4.200.106:6853 socket closed (con state CONNECTING)
> Sep 22 12:35:18 iris-gaia-blue-20230922-worker01 kernel: libceph: osd691 (1)10.4.200.118:6801 socket closed (con state CONNECTING)
> Sep 22 12:35:18 iris-gaia-blue-20230922-worker01 kernel: libceph: osd675 (1)10.4.200.106:6849 socket closed (con state CONNECTING)
> Sep 22 12:37:21 iris-gaia-blue-20230922-worker01 kernel: libceph: osd686 (1)10.4.200.112:6837 socket closed (con state CONNECTING)
> Sep 22 12:37:21 iris-gaia-blue-20230922-worker01 kernel: libceph: osd703 (1)10.4.200.118:6849 socket closed (con state CONNECTING)
> Sep 22 12:37:21 iris-gaia-blue-20230922-worker01 kernel: libceph: osd672 (1)10.4.200.106:6837 socket closed (con state CONNECTING)
> Sep 22 12:37:21 iris-gaia-blue-20230922-worker01 kernel: libceph: osd680 (1)10.4.200.112:6813 socket closed (con state CONNECTING)
> Sep 22 12:37:25 iris-gaia-blue-20230922-worker01 kernel: libceph: osd684 (1)10.4.200.112:6829 socket closed (con state CONNECTING)
> Sep 22 12:37:25 iris-gaia-blue-20230922-worker01 kernel: libceph: osd667 (1)10.4.200.106:6817 socket error on write
> Sep 22 12:37:25 iris-gaia-blue-20230922-worker01 kernel: libceph: osd694 (1)10.4.200.118:6813 socket error on read
>

**Comment by Zarquan** [comment]
@stvoutsin  Is this still a problem ?

**Comment by stvoutsin** [comment]
This is now fixed.
Email from P.Browne:
> 
On a closer inspection, I suspect this was due to an internal routing issue, where some newly added Ceph cluster hosts did not contain a reciprocal route back to the cloud infrastructure. This has now been rectified, if you could please again from a fresh instance mount state.
