### ISSUE TITLE
(Python) Healthchecker for Zeppelin

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#150]
Build a Python Healthchecker library, that simply runs a sample Notebook Cell using the Spark Interpreter, and checks for the error message that we've been seeing with the tmp directory files not found: .
" IOException: Failed to create local dir in /tmp/hadoop-fedora/nm-local-dir/usercache/fedora/appcache/applicatio ..."

If exception is triggered, then we need to restart the Spark Interpreter, which can be done as seen here:
https://zeppelin.apache.org/docs/0.8.0/usage/rest_api/interpreter.html#restart-an-interpreter

This would have to be done using the admin account, so the HTTP request needs to be authorized accordingly.

We need to log the output of the healthchecker in a shared folder that we can follow, to see how often the exception is triggered.

**Comment by stvoutsin** [comment]
I've started working on this here:
https://github.com/stvoutsin/aglais-healthchecker

**Comment by Zarquan** [comment]
@stvoutsin Could you add a bit more description about what this does and why we need it ?
