### ISSUE TITLE
Change test control

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#601]
PR #590 introduced a 3rd parameter to the create-all script to control whether the tests were run.
Initial version sets a variable called `deploytype` which defaults to `prod` and needs to be set to `test` to trigger the tests.

This explicitly links the testing and the type of deployment, implying we don't test a live deployment.
We should revisit this and change it from `deploytype` to something like `testlevel`, which controls the _amount_ of testing that is performed.

Suggested values would be things like `basic`, `quick`, `long`, and `stress` ?
We use this to modify the that are passed to the test program, including the list of tests and the number of concurrent users.

As an initial suggestion, `quick` testing could include the source counts and proper motion notebooks, `basic` testing could add the random forest classifier, and `long` testing could include the newer ML notebooks.

**Comment by stvoutsin** [comment]
These options are now included and used by the benchmarks
