### ISSUE TITLE
AglaisBenchmarker results output as JSON 

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#602]
We need the test results output as a valid JSON object that can be combined into larger documents and parsed with `jq`.

**Comment by Zarquan** [comment]
The current test program outputs a mixture of text and (invalid) JSON.
* First line of the output is plain text
* Second line of output looks like JSON, but uses single quotes where it should use double quotes
* JSON output should be pretty-printed

Current output:

    cat test-result.json
        Test completed after: 8079.32 seconds
        {'SetUp': {'totaltime': '44.83', ....

Fixes needed to read it as JSON:

    cat test-result.json | sed '1 d'  | sed "s/'/\"/"g | jq '.'

        {
          "SetUp": {
            "totaltime": "44.83",
            "status": "SUCCESS",
            "msg": "",
            "valid": "TRUE"
          },
         ....
        }

**Comment by Zarquan** [comment]
The output from the latest version requires the following `sed` script to make it readable by `jq`.
```
    sed "
        1,3 d
        s/\"/#/g
        s/'\(-\{0,1\}[0-9.]\{1,\}\)'/\1/g
        s/:[[:space:]]*\([a-zA-Z]\{1,\}\)\([,}]\)/:'\1'\2/g
        s/:[[:space:]]*\([,}]\),/: ''\1/g
        s/'/\"/g
        " \
        '/tmp/test-result.json'
```

Please make the test output valid JSON readable by `jq`.

**Comment by Zarquan** [comment]
This is hampering the concurrent testing.
Having to post-process the output using `sed` makes it difficult to put use `AglaisBenchmarker` as a component in test loops.

**Comment by Zarquan** [comment]
I think this is done .. need to check.

**Comment by stvoutsin** [comment]
Output should now be JSON 
For example:
https://github.com/stvoutsin/gaia-dmp/blob/68b38d0b58b965dc80d4eda19718ed9dcd9bcda6/notes/stv/20221102-run-benchmarks-01.txt#L207
