### ISSUE TITLE
Customize Zeppelin Home Screen (Gaia look & feel)

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#659]
Specifically, we'd like to be able to add the Gaia Logo, and change the "Welcome to Zeppelin" message

**Comment by stvoutsin** [comment]
https://stackoverflow.com/questions/32791384/is-it-possible-to-customize-the-skin-on-zeppelin

**Comment by stvoutsin** [comment]
Customizing any of the Homescreen would require the following steps:

"""
Check out zeppelin source code (e.g. from GitHub https://github.com/apache/zeppelin ). Then:

To customize the front page (which has a "Welcome to Zeppelin" on it): edit zeppelin-web/src/app/home/home.html

To customise the navbar (which contains a small zeppelin logo and the word zeppelin): edit zeppelin-web/src/components/navbar/navbar.html

After that you need to rebuild zeppelin mvn clean install -DskipTests (note that you may need to force reload in the browser).
"""

We'd then have to store the binaries produced from our build somewhere, and modify our scripts to use that.
We'd also have to maintain the forked version of the zeppelin sourcecod & update accordingly.

This can all be done, but probably would take time away from other more critical tasks for DR3 milestone 1, so my suggestion is leave it for later.

**Comment by stvoutsin** [comment]
I've worked on customizing Zeppelin for Gaia, notes and changes for this can be found here:
https://github.com/wfau/gaia-dmp/compare/master...stvoutsin:gaia-dmp:upgrade/customise-zeppelin

And the Zeppelin code:
https://github.com/stvoutsin/zeppelin/tree/0.10.0-dev

A couple of questions:
- I've fetched version 0.10 to match what we are using for prod, but do we instead want to apply these customizations to the newest version (0.11) ? Note that I don't see this as an official release anywhere yet
- The Zeppelin build has been uploaded to the Openstack (Arcus) S3 instance. Is this ok, or do we want to place it somewhere else?
- What needs to be done for this to be merged in to the main repo?

**Comment by Zarquan** [comment]
Could you add your screen shots to this discussion.

**Comment by Zarquan** [comment]
Could we include a 'watermark' for test deployments ?
See #1027.

**Comment by stvoutsin** [comment]
![gdmp1](https://user-images.githubusercontent.com/10408723/213497002-907a8733-6ce3-4222-9360-2fc1ccffcbcf.png)
![gdmp2](https://user-images.githubusercontent.com/10408723/213497015-815c1526-2059-407e-89e1-381602c61d0e.png)
![gdmp3](https://user-images.githubusercontent.com/10408723/213497020-16f704b2-6d89-46cf-8940-f537f9f356c3.png)

**Comment by stvoutsin** [comment]
This is now included in the version on main
