### ISSUE TITLE
Website maintenance mode

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#704]
We need to be able to 'lock' the website, preventing people from logging in, while the site is down for maintenance and during  the transfer to a new deployment.

The stages for a new deployment should be something like this :

* Single command to lock the 'old' site, users can't login.
* New deployment is activated with admin users only.
* Transfer of home directories and notebooks.
* Testing and checks.
*  New site is opened up to all users.

**Comment by Zarquan** [comment]
One way of doing this might be to manipulate the Shiro database, disabling the 'user' accounts but leaving the 'admin' accounts active.

**Comment by Zarquan** [comment]
Alternatively, we could replace or redirect external access using the HTTP proxy we plan to implement. This might be better because we could display a user friendly page saying _"the site is down for maintenance"_ rather than just a failed login.

**Comment by stvoutsin** [comment]
Is this sufficient for this issue:
https://github.com/wfau/gaia-dmp/pull/1161
?
