### ISSUE TITLE
Add zeppelin to /etc/hosts on the client

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#747]
If we add the public IP address of the `zeppelin` node to `/etc/hosts` in the client contaner, then everything else can just use `zeppelin` as the hostname and it will resolve.

This includes our test tools, which can simply be configured to use `http://zeppelin:8080/` as the service endpoint.

The best place to add this is in the `06-config-dns.yml` Ansible playbook, which configures `/etc/hosts` on the remote nodes.

**Comment by stvoutsin** [comment]
I've ran a test deploy with the most recent version of gdmp & can confirm that zeppelin is now added to the hosts file, so closing this as done. Re-open if you disagree with this
