### ISSUE TITLE
Failed Spark tasks in large Parquet ingest 

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#807]
Email from Nigel :
> Well the ingest has finished without error in the Zeppelin UI after 10.5 hours, and there are 2048 partition parquet files as I would expect, totalling 5.6 TB.
> However looking in the Spark UI there seem to be some failed stages and retrys; most worryingly the final stage seems to be stuck in retry #3 with the word “killed”. AFAICS the retrys are due to connection drops on workers 05, 10 and 11.

Injest worked, so this is not critical. Logging it here so that we can keep track if/when similar issues occur.
cloud : iris-gaia-blue

**Comment by Zarquan** [comment]
This might be a duplicate of #806, in which case apologies, close this one.

**Comment by NigelHambly** [comment]
second biggest DR3 ingest (2.7 T) is suffering hiccups and getting re-queued, eg.

org.apache.spark.shuffle.FetchFailedException: Failed to send RPC RPC 8034356249107714764 to worker08/10.10.3.70:7337: java.io.IOException: Broken pipe

IIUC what the Spark UI is telling me, it's re-queuing the entire stage not individual worker processing of partitions. This will take ages. Wonder if we're suffering network file system glitches here?

**Comment by NigelHambly** [comment]
ExecutorLostFailure (executor 126 exited caused by one of the running tasks) Reason: Container from a bad node: container_1656596967503_0003_01_000142 on host: worker08. Exit status: 137. Diagnostics: [2022-07-01 18:25:19.901]Container killed on request. Exit code is 137
[2022-07-01 18:25:19.903]Container exited with a non-zero exit code 137. 
[2022-07-01 18:25:19.904]Killed by external signal

Looks like it's an OOM (code 137): https://aws.amazon.com/premiumsupport/knowledge-center/container-killed-on-request-137-emr/

I think this could mean our partitions are too big ( > 1G in this case). We may need to repartition everything... argh.

**Comment by NigelHambly** [comment]
Let's leave it to see if it completes successfully anyway.

**Comment by Zarquan** [comment]
If we look in the logs from the Spark interpreter on the Zeppelin node, we see lots of these messages:

```
[zeppelin]
less zeppelin-interpreter-spark-nch-nch-fedora-iris-gaia-blue-20220627-zeppelin.log
    ....
    ....
    WARN [2022-07-01 22:55:07,695] ({task-result-getter-1}
        Logging.scala[logWarning]:69) - 
        Lost task 14.0 in stage 7.3 (TID 69262)
        (worker07 executor 132): FetchFailed(
            BlockManagerId(
                106, worker03, 7337, None
                ),
            shuffleId=1,
            mapIndex=27,
            mapId=6040,
            reduceId=1346,
            message=
                org.apache.spark.shuffle.FetchFailedException: Connection from worker03/10.10.0.224:7337 closed
                    at org.apache.spark.storage.ShuffleBlockFetcherIterator.throwFetchFailedException(ShuffleBlockFetcherIterator.scala:770)
                    at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:685)
                    at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:70)
                    ....
                    ....
                Caused by: java.io.IOException: Connection from worker03/10.10.0.224:7337 closed
                    at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
                    at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:117)
                    ....
                    ....
            )
    INFO [2022-07-01 22:55:07,695] ({task-result-getter-1}
        Logging.scala[logInfo]:57) - 
        task 14.0 in stage 7.3 (TID 69262) failed, but the task will not be re-executed
        (either because the task failed with a shuffle data fetch failure, so the previous stage
        needs to be re-run, or because a different copy of the task has already succeeded).
    ....
    ....
```

**Comment by Zarquan** [comment]
Checking the nodemanager logs on worker03 for around the same time :

```
[worker03]
less hadoop-fedora-nodemanager-iris-gaia-blue-20220627-worker03.log
    ....
    ....
    2022-07-01 22:55:07,682 ERROR org.apache.spark.network.server.ChunkFetchRequestHandler:
        Error sending result ChunkFetchSuccess[
            streamChunkId=StreamChunkId[
                streamId=345457820819,chunkIndex=280
                ],
            buffer=FileSegmentManagedBuffer[
                file=/mnt/cinder/vdd/hadoop/data/usercache/nch/appcache/application_1656596967503_0003/blockmgr-b4302fcd-b40e-4ce3-8850-3277221d0e84/13/shuffle_1_49481_0.data,offset=35427019,
                length=5454
                ]
            ] to /10.10.1.1:35162; closing connection
        java.io.FileNotFoundException:
            /mnt/cinder/vdd/hadoop/data/usercache/nch/appcache/application_1656596967503_0003/blockmgr-b4302fcd-b40e-4ce3-8850-3277221d0e84/0e/shuffle_1_17065_0.data
            (No such file or directory)
                at java.io.RandomAccessFile.open0(Native Method)
                at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
                at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)

    ....
    ....
```

**Comment by Zarquan** [comment]
Checking the application logs on worker07 for around the same time :

```
[worker07]
less application_1656596967503_0003/container_1656596967503_0003_01_000134/stderr
    ....
    ....
    2022-07-01 22:55:07,327 INFO shuffle.RetryingBlockFetcher: Retrying fetch (3/3) for 389 outstanding blocks after 5000 ms
    2022-07-01 22:55:07,327 ERROR shuffle.OneForOneBlockFetcher: Failed while starting block fetches
    java.io.IOException: Connection from worker03/10.10.0.224:7337 closed
        at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:146)
        at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:117)
    ....
    ....
    2022-07-01 22:55:08,493 WARN server.TransportChannelHandler: Exception in connection from worker03/10.10.0.224:7337
    java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        ....
        ....
    2022-07-01 22:55:08,493 ERROR client.TransportResponseHandler: Still have 157 requests outstanding when connection from worker03/10.10.0.224:7337 is closed
    2022-07-01 22:55:08,493 INFO shuffle.RetryingBlockFetcher: Retrying fetch (3/3) for 104 outstanding blocks after 5000 ms
    2022-07-01 22:55:08,493 INFO shuffle.RetryingBlockFetcher: Retrying fetch (3/3) for 53 outstanding blocks after 5000 ms
    ....
    ....
```

**Comment by Zarquan** [comment]
We see hundreds of these log messages, on all the workers.

One of the workers is unable to find a file in it's cache, it can't send any data so it closes the connection to the worker that is waiting for that block. The worker at the other end of the connection logs an error and then tries again from another source.
We see this pattern repeated over and over again.

All of the workers are reporting file not found Exceptions looking for files in their local data cache.

**Comment by Zarquan** [comment]
I might be looking at the wrong things. The log messages Nigel's reported are around `18:25:19`. The log messages I've been looking at are for `22:55:07` so they might not be related at all.

**Comment by Zarquan** [comment]
If the nodes really were loosing files from the Cinder volumes, I'd expect to see lots of dire warnings in the system logs, but we don't.

**Comment by Zarquan** [comment]
What we do see are messages about the OutOfMemory reaper killing off processes that are taking up too much memory :
```
[worker06]
sudo journalctl

    Jul 01 20:10:47 iris-gaia-blue-20220627-worker06 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-5.scope,task=java,pid=11623>
    Jul 01 20:10:47 iris-gaia-blue-20220627-worker06 kernel: Out of memory: Killed process 11623 (java) total-vm:9011400kB, anon-rss:7206812kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:14768kB oom_score_adj:0
    Jul 01 20:10:47 iris-gaia-blue-20220627-worker06 systemd[1]: session-5.scope: A process of this unit has been killed by the OOM killer.
    Jul 01 20:10:47 iris-gaia-blue-20220627-worker06 kernel: oom_reaper: reaped process 11623 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by NigelHambly** [comment]
OK: the ingest eventually failed after bravely retrying for 12 hours. The exception trace passed back includes

Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: ResultStage 7 (saveAsTable at NativeMethodAccessorImpl.java:0) has failed the maximum allowable number of times: 4

I'm going to up the number of partitions by a factor 4x and thereby decrease their size by the same factor to see if it's happier. I can't restart Spark (to flush the hadoop user caches and other extraneous cruft) so this could be in vain. However the Spark UI is showing all nodes as healthy, and a spot check of available space on the worker nodes /var/hadoop seems to indicate there's plenty of spare capacity... so fingers crossed and here goes....

**Comment by NigelHambly** [comment]
Up to 5pm BST 2/07/22 everything seemed to be going fine: first stage (1 of 2) read ran for 7.5 hours with no failures or exceptions. The job then transitioned to the writeTable stage (2 of 2; 8192 tasks, one per partition presumably) and immediately workers 03, 07 and 12 started dropping connections and causing task failures. Looks like it's reverted to a retry of stage 1 if I'm reading the Spark UI correctly. 

Here's an example excerpt from the exception trace:

FetchFailed(BlockManagerId(227, worker12, 7337, None), shuffleId=2, mapIndex=96, mapId=73016, reduceId=27, message=
org.apache.spark.shuffle.FetchFailedException: Connection from worker12/10.10.1.62:7337 closed

I'll leave it running as it is reporting successful completion of some tasks IIUC...

**Comment by NigelHambly** [comment]
No dice:

Py4JJavaError: An error occurred while calling o754.saveAsTable.
: org.apache.spark.SparkException: Job aborted.
.
.
.
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: ResultStage 11 (saveAsTable at NativeMethodAccessorImpl.java:0) has failed the maximum allowable number of times: 4. Most recent failure reason: org.apache.spark.shuffle.FetchFailedException: Connection from worker02/10.10.1.253:7337 closed 

I give up.

**Comment by Zarquan** [comment]
Starting with worker03, we see lots of [ChunkFetchRequestHandler error] messages, caused by [IOException: Broken pipe] from other workers.
```
[worker03]
less hadoop-fedora-nodemanager-iris-gaia-blue-20220627-worker03.log

    2022-07-02 17:10:46,233 ERROR org.apache.spark.network.server.ChunkFetchRequestHandler:
        Error sending result ChunkFetchSuccess[
            streamChunkId=StreamChunkId[
                streamId=345457831555,
                chunkIndex=327
                ],
            buffer=FileSegmentManagedBuffer[
                file=/mnt/cinder/vdd/hadoop/data/usercache/nch/appcache/application_1656596967503_0003/blockmgr-d59315e2-042c-4954-8831-7b13ab7a85ed/1e/shuffle_2_114181_0.data,
                offset=4873911,
                length=5455
                ]
            ] to /10.10.3.204:54516; closing connection
        java.nio.channels.ClosedChannelException
            at org.sparkproject.io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
            at org.sparkproject.io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
            ....
            ....
        Caused by: java.io.IOException: Broken pipe
            at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
            at sun.nio.ch.FileChannelImpl.transferToDirectlyInternal(FileChannelImpl.java:428)
            at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:493)
            at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:605)
            ....
            ....
```

We also see reports of Yarn killing a container (transitioned from RUNNING to KILLING) and returning an exit code of 143.
```
[worker03]
less hadoop-fedora-nodemanager-iris-gaia-blue-20220627-worker03.log

    ....
    2022-07-02 17:19:27,795 INFO org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService: Cache Size Before Clean: 699190514, Total Deleted: 0, Public Deleted: 0, Private Deleted: 0
    2022-07-02 17:20:22,518 INFO org.apache.hadoop.yarn.server.nodemanager.containermanager.container.ContainerImpl: Container container_1656596967503_0003_01_000176 transitioned from RUNNING to KILLING
    2022-07-02 17:20:22,519 INFO org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerCleanup: Cleaning up container container_1656596967503_0003_01_000176
    2022-07-02 17:20:22,627 WARN org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor: Exit code from container container_1656596967503_0003_01_000176 is : 143
```

In this particular case it was worker04 (10.10.3.204) that closed the connection.

Looking at the logs on worker04, lots of [ChunkFetchRequestHandler error sending result ChunkFetchSuccess] messages, caused by [IOException: Broken pipe] from other workers.
```
[worker04]
less /var/hadoop/logs/hadoop-fedora-nodemanager-iris-gaia-blue-20220627-worker04.log 

    2022-07-02 17:06:32,639 ERROR org.apache.spark.network.server.ChunkFetchRequestHandler:
        Error sending result ChunkFetchSuccess[
            streamChunkId=StreamChunkId[
                streamId=1914535228355,
                chunkIndex=508
                ],
            buffer=FileSegmentManagedBuffer[
                file=/mnt/cinder/vdd/hadoop/data/usercache/nch/appcache/application_1656596967503_0003/blockmgr-0a933116-0a26-4646-8ae1-e0e5ad4f415f/07/shuffle_2_129399_0.data,
                offset=4592934,
                length=10778
                ]
            ] to /10.10.3.12:57430; 
        closing connection
        java.nio.channels.ClosedChannelException
            at org.sparkproject.io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
            at org.sparkproject.io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
            ....
            ....
        Caused by: java.io.IOException: Broken pipe
            at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
            at sun.nio.ch.FileChannelImpl.transferToDirectlyInternal(FileChannelImpl.java:428)
            at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:493)
            at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:605)
            ....
            ....
```

We also see lots of [TransportRequestHandler error sending result RpcResponse] messages, again caused by [IOException: Broken pipe] from other workers.
```
[worker04]
less /var/hadoop/logs/hadoop-fedora-nodemanager-iris-gaia-blue-20220627-worker04.log 

    2022-07-02 17:10:38,867 ERROR org.apache.spark.network.server.TransportRequestHandler:
        Error sending result RpcResponse[
            requestId=7438252237462261820,
            body=NioManagedBuffer[
                buf=java.nio.HeapByteBuffer[
                    pos=0
                    lim=13
                    cap=13
                    ]
                ]
            ] to /10.10.0.5:46454; closing connection
        java.nio.channels.ClosedChannelException
            at org.sparkproject.io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
            at org.sparkproject.io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
            ....
            ....
        Caused by: java.io.IOException: Broken pipe
            at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
            at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
            at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
            at sun.nio.ch.IOUtil.write(IOUtil.java:65)
            ....
            ....
```

**Comment by Zarquan** [comment]
Can we try repeating one of the smaller data sets, one that we know worked. Rename the directory of shiny new parquet files and run the job again. Just to check that the issue is the size of the data and not a broken configuration.

**Comment by NigelHambly** [comment]
IIUC Yarn exit code 143 is memory overhead-related again.

I have a wheeze. 

I'm assuming that the data are uniformly spread over the partitions for the data set I'm trying to ingest, which has been the case for the others, but may not be so for this troublesome one. If the data is concentrated in many fewer partitions (it is a 0.1% sampling of all sources; we're partitioning by source ID ...) then individual partitions may be pushing close to or over the limit, resulting in this problem... I'll take a closer look at the repartitioning algorithm and the number of partitions implied for this sampled data...

**Comment by NigelHambly** [comment]
Don't think my wheeze is relevant. The data should be uniformly distributed on the partitioning key as per the existing successful ingests. I misunderstood the documentation: the data in question are not a 0.1% sample.

One other thing to keep in mind is that I can't restart Spark following these failures. This means that, despite what's reported in the Spark UI, the system may be munged in such a way that once it's failed it cannot recover, and anything I try from that point on is doomed to failure until Spark is given a kick. Last time we went through all this I would restart the interpreter to clear things up in between each big ingest job. Dunno why the button to do this doesn't work for me in Zeppelin any more, but it's a p-in-the-a having to bug one of you guys to do it (especially outside normal working hours when it's unreasonable to expect an instant response of course).

I've just launched a new ingest of the troublesome data but selecting only one in ten files, so a 10% sized ingest, which is well below the size of ones we've done successfully with the current system.

**Comment by NigelHambly** [comment]
It worked for 10% of the data, but 2 stages needed a couple of re-tries due to lost connections. Partitions (8192) are all around 35 MB, so the fully monty would have 350 MB partitions if we could get it to run successfully.

**Comment by NigelHambly** [comment]
Q: during the job I see a large number (250) of tasks running concurrently. What's the config of OpenStack VMs, how does it map to the physical hardware, in particular the (shared?) memory available to the cores?

**Comment by Zarquan** [comment]
Not sure why Zeppelin won't let you restart the interpreter on your notebook. Need to check with Stelios on this, but each user should get their own interpreter, so I can't stop/start your interpreter.

**Comment by Zarquan** [comment]
Did some more digging into the probable causes of this.

Found a really useful explanation of what might be happening (same article twice)
* [4 Common Reasons for FetchFailed Exception in Apache Spark](https://dzone.com/articles/four-common-reasons-for-fetchfailed-exception-in-a)
* [Fetch Failed Exception in Apache Spark: Decrypting the most common causes](https://towardsdatascience.com/fetch-failed-exception-in-apache-spark-decrypting-the-most-common-causes-b8dff21075c)

We do get some error messages that match this pattern. Not a huge amount, so it might no be the primary cause.
* [Container killed on request. Exit code is 137](http://worker10:8042/node/containerlogs/container_1656596967503_0003_01_000001/nch/stderr/?start=0)
```
2022-07-01 18:25:20,243 INFO yarn.YarnAllocator: Received 1 containers from YARN, launching executors on 1 of them.
2022-07-01 18:25:20,246 INFO yarn.YarnAllocator: Completed container container_1656596967503_0003_01_000142 on host: worker08 (state: COMPLETE, exit status: 137)
2022-07-01 18:25:20,248 WARN yarn.YarnAllocator: Container from a bad node: container_1656596967503_0003_01_000142 on host: worker08. Exit status: 137. Diagnostics: [2022-07-01 18:25:19.901]Container killed on request. Exit code is 137
[2022-07-01 18:25:19.903]Container exited with a non-zero exit code 137.
[2022-07-01 18:25:19.904]Killed by external signal
```

According to the Amazon documentation Nigel found, we just need to increase the executor memory. Might not be that simple, as we would have to juggle the rest of the resource limits to make space.
* [How do I resolve "Container killed on request. Exit code is 137" errors in Spark on Amazon EMR?](https://aws.amazon.com/premiumsupport/knowledge-center/container-killed-on-request-137-emr/)

Curious as to why we don't see a lot of OutOfMemoryExceptions in the logs.

This might help to explain it
* [What happens when OutOfMemory Error happens on spark container](https://stackoverflow.com/questions/52951399/what-happens-when-outofmemory-error-happens-on-spark-container)
> I see a whole bunch of connection refused during block fetches and one out of memory error. Hard to tell what is the underlying cause

Turns out that Spark adds an `OnOutOfMemoryError` option to the application/container launcher that kills the process as soon as it gets an `OutOfMemoryException`. This is the code that gets run on a worker node to launch an application/container.
```
    exec \
        /bin/bash \
            -c "
                $JAVA_HOME/bin/java \
                    -server \
                    -Xmx6144m \
                    -Djava.io.tmpdir=$PWD/tmp \
                    '-Dspark.driver.port=35817' \
                    -Dspark.yarn.app.container.log.dir=/var/hadoop/logs/application_1656596967503_0003/container_1656596967503_0003_01_000009 \
                    -XX:OnOutOfMemoryError='kill %p' \
                    org.apache.spark.executor.YarnCoarseGrainedExecutorBackend \
                    --driver-url spark://CoarseGrainedScheduler@zeppelin:35817 \
                    --executor-id 8 \
                    --hostname worker09 \
                    --cores 4 \
                    --app-id application_1656596967503_0003 \
                    --resourceProfileId 0 \
                    --user-class-path file:$PWD/__app__.jar \
                    1>/var/hadoop/logs/application_1656596967503_0003/container_1656596967503_0003_01_000009/stdout \
                    2>/var/hadoop/logs/application_1656596967503_0003/container_1656596967503_0003_01_000009/stderr
                "
```
Key part is
```
                    -XX:OnOutOfMemoryError='kill %p' \

```

I suspect that this is killing the process before it can log the `OutOfMemoryException`, which might explain why we see lots of `FetchFailedException` caused by closed or broken connections, but very few `OutOfMemoryException`. 

The code that adds this option to the command line is here
https://github.com/Zarquan/aglais-spark/blob/master/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/YarnSparkHadoopUtil.scala#L104-L130

We should be able to override the default and add our own code to log the event before killing the process, as suggested [here](https://stackoverflow.com/a/49458175) by adding our own version of the `OnOutOfMemoryError` hook by adding it to  `spark.executor.extraJavaOptions` in our Spark configuration.

**Comment by Zarquan** [comment]
I've rebooted all the services, using the same procedure as before
https://github.com/Zarquan/aglais/blob/20220624-zrq-red-deploy/notes/zrq/20220630-02-blue-reboot.txt

I've added a script to log OOM events to the worker nodes
```
cat > /tmp/OOMhandler.sh << EOF
p=\$1
/bin/echo "[\$(/bin/date -Is)] [\$p]"  >> /tmp/OOMhandler.log
kill \$p
EOF
```
and I've added the `OnOutOfMemoryError` option  to the end of `/opt/spark/conf/spark-defaults.conf` on the Zeppelin node.
```
spark.executor.extraJavaOptions=-XX:OnOutOfMemoryError='/tmp/OOMhandler.sh %p'
```

It doesn't seem to get in the way of running a normal notebook like one of the public examples.
 
Over to you Nigel to see if you can trigger it by running your partitioning notebook.

Run the notebook as normal, and if/when it fails check `/tmp/OOMhandler.log` on the workers to see if the handler logged  anything.

If the handler logs an OOM event for the failed jobs then we know this is what is causing the problem and we can look at increasing the available memory for the executors, or increasing the number of partitions, splitting the data into more smaller partitions.

**Comment by stvoutsin** [comment]
I've tried running the ingest again with the following settings, and it failed with the same symptoms
```
core-site.xml :
<property>
    <name>hadoop.tmp.dir</name>
    <value>/var/hadoop/data</value>
</property>
```

```
yarn-site.xml
<property>
    <name>yarn.nodemanager.resource.memory-mb</name>
    <value>40960</value>
</property>

<property>
    <name>yarn.nodemanager.resource.cpu-vcores</name>
    <value>26</value>
</property>
  
```

Spark Settings:
```
# Calculated using Cheatsheet.xlsx
spark.driver.memory                 57344m
spark.driver.memoryOverhead           9216
spark.driver.cores                       5
spark.driver.maxResultSize          40960m

spark.executor.memory                4096m
spark.executor.memoryOverhead         1024
spark.executor.cores                     4
#spark.executor.instances               30

spark.default.parallelism              576
#spark.sql.shuffle.partitions          300

# YARN Application Master settings
spark.yarn.am.memory                 2048m
spark.yarn.am.cores                      1

spark.dynamicAllocation.enabled          true
spark.shuffle.service.enabled            true
spark.dynamicAllocation.minExecutors      1
 # spark.executor.instances from Cheatsheet
spark.dynamicAllocation.maxExecutors     72
 # maxExecutors / 2
spark.dynamicAllocation.initialExecutors          15
spark.dynamicAllocation.cachedExecutorIdleTimeout 60s
spark.dynamicAllocation.executorIdleTimeout       60s
spark.sql.execution.arrow.pyspark.enabled            true

```

Note: yarn.scheduler settings have been commented out

**Comment by Zarquan** [comment]
The Slack image URL doesn't work outside Slack.
![worker03](https://user-images.githubusercontent.com/4954609/177900050-000deb6d-13d5-4865-8e33-e74fef4fd220.png)

**Comment by NigelHambly** [comment]
@stvoutsin has suggested a work-around, viz. processing the csv files into dataframes in batches then writing out to parquet in append mode. For example, we can read *0.csv, *1.csv, .... *9.csv in a loop meaning that only 10% of the data needs to be processed at a time. This may get us over the immediate ingest hurdle, provided we don't go over the partition file size limit (#952).

Will try this out, but not on the live production system (don't want to lock that up for our new users)... @Zarquan : which test deploy? (don't seem to be able to access green... was it torn down after NAM?)

**Comment by NigelHambly** [comment]
Latest from @stvoutsin:

"I ran the full ingest for the "mcmc_samples_gsp_phot" table overnight, with buckets = 2048 and again while I was expecting it to fail, it worked fine. I've also verified the row count and it is indeed: 449297716 rows.
This was run on a 6 worker node Spark cluster, less than the 12 node big cluster we created for you last time, so perhaps there was something wrong with that one? The job ran in aprox. 10 hours.

I'm currently copying over the parquet files to an external data share so that they are persisted. Once that's done we can create a test cluster for you to use and verify that table, or run ingest jobs for the other tables as well. 
The partition size for these parquet files is 1.44Gb, if you think that is too big we can try running that job with more buckets. Not sure if we'll be running into those failed job issues again or not, I wasn't expecting this one to work and it did, which means it may be hard to consistently replicate the error, if it even is there for the 6 worker node cluster, which is what we are also currently using for the live service."

**Comment by NigelHambly** [comment]
I increasingly suspect the problem is in the level of parallelism resulting from the configuration of the "big" machine set up resulting in the memory over-commits.

Anyway, a double check on row counts from @stvoutsin 's latest successful ingest:

- for mcmc_samples_gsp_phot the row count is logged in the relevant [Gaia DPAC CU9 ops Jira](https://issues.cosmos.esa.int/gaia/browse/C9OPS-961) as 449,297,716 rows;
- the total number of lines in the csv files is 449,836,090 including 159 header lines in each of 3386 files, implying a (consistent) row count of 449,836,090 - (3386 x 159) = 449,297,716.

So looks like all is well on a standard-sized machine to ingest in one go (i.e. without chopping up into e.g. 10% sized batches) regardless of the resulting rather large partition size in this particular case (indeed the already successfully ingested xp_continuous_mean_spectrum has this partition file size). 

I suggest that I now finish off the ingests on such a standard-sized machine... but not the live production machine potentially being used by our news users. Please advise which test machine to use when ready, and it's Zeppelin UI IP or DNS name.

**Comment by NigelHambly** [comment]
Now progressing this on test deploy at end point http://128.232.227.147/

The two remaining large ingests (mcmc_samples_XX) have been successfully done with no problems.
 
N.B. decided to fill in all outstanding tables in the DR3 schema, and in the process of sorting this out discovered #1009

**Comment by NigelHambly** [comment]
Ingests complete. This issue can be closed.

**Comment by NigelHambly** [comment]
Reopening to clarify a few things

- an attempt to repartition one of the large datasets (xp_continuous_mean_spectrum, 2.7T) 18 months down the line from all the above shenanigans revealed some confusion as to what the problems are with these scale-out ingests and how to work around them;
- the key thing to note is that repartitioning requires a large work space on disk, equal in size to the size of the data being repartitioned, aggregated in the /var/hadoop/data volumes across the cluster workers (locally attached ephemeral storage will be likely insufficient so scale-up volumes have to be set up on CephFS for example). If these volumes become more than 90% full the repartition process will fail (possibly even with a total lock-up in the system)
- that space remains in use as long as the pyspark interpreter is active for the relevant processing notebook (it will clear on restarting the interpreter for example)
As long as the above is duly considered then repartitioning, e.g. into 32768 as opposed to 2048 partitions, is perfectly feasible. For example xp_continuous_mean_spectrum has been partitioned into 32678 files by reading from the original eCSV files, bucketed and sorted by source ID into parquet, in 7.5 hours on a six-node system configured with /var/hadoop/data volumes on CephFS.

Note that in the course of investigating this, I tried to do a 10% piece-wise ingest (as suggested above may be a work-around for very large data sets) but could not get this to work - it appears that saving data to parquet files with bucketing and sorting is not supported in pyspark with the mode = "append" option.
