### ISSUE TITLE
Hadoop out of disk space on /vdd (/var/hadoop/temp). Need to move hadoop/temp (& hadoop/logs) to mounted 1Tb disk

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#817]
New attempt to run an ingest failed, but for a different reason this time:

> 1/1 local-dirs usable space is below configured utilization percentage/no more usable space [ /var/hadoop/temp/nm-local-dir : used space above threshold of 90.0% ] ; 1/1 log-dirs usable space is below configured utilization percentage/no more usable space [ /var/hadoop/logs/userlogs : used space above

Note that this is not /var/hadoop/data which had the extra 1Tb disk that filled up, it was instead the /vdb mount which is the small 178G disk. It seems that hadoop writes out results of the map/reduce process to /var/hadoop/temp which is what filled up. I suggest if we come use the mounted 1 Tb share for all hadoop directories (/temp, /data & /logs).

**Comment by NigelHambly** [comment]
The Zeppelin UI shows the job as still running AFAICS. But don't worry about this for now. Do the other higher priority stuff.

**Comment by Zarquan** [comment]
If we put everything on one disc, then we don't know which one is using up space.
We can check how much space each of the directories has used and then create separate Cinder mounts for each one.

**Comment by stvoutsin** [comment]
We're currenly working on setting up HTTPS & NGINX for our deployments which is almost there so not debugging this currently. However the job will most likely not complete, as all nodes are inactive, due to no available disk for /var/hadoop/temp

**Comment by stvoutsin** [comment]
Some more info:
/vdb which is the 170 disk (vdb) was full (close to 90%+), and it was fulll from files being written to /var/hadoop/temp/nm-local-dir/usercache/nch
/vdd which is mounted on /vad/hadoop/data saw usage between 0 - 30% on the various worker nodes

> The tmp directory mainly used as a temporary storage during mapreduce operation. Mapreduce artifacts, intermediate data etc will be kept under this directory. These files will be automatically cleared out when mapreduce job execution completes. If you delete this temporary files, it can affect the currently running mapreduce jobs.

https://stackoverflow.com/questions/24885881/what-is-tmp-directory-in-hadoop-hdfs

**Comment by Zarquan** [comment]
By the time I ran this the workflow had moved on and the original data had been deleted. Next time it runs into this issue can we run something like this to get some detailed numbers.

```
    nodes=(
        zeppelin
        master01
        worker01
        worker02
        worker03
        worker04
        worker05
        worker06
        worker07
        worker08
        worker09
        worker10
        worker11
        worker12
        )

    for node in ${nodes[@]}
    do
        echo "---- ----"
        ssh "${node}" \
            '
            hostname
            du -h -d 0 /var/hadoop/logs/
            du -h -d 0 /var/hadoop/temp/
            du -h -d 0 /var/hadoop/data/
            '
    done

    for node in ${nodes[@]}
    do
        echo "---- ----"
        ssh "${node}" \
            '
            hostname
            df -h /var/hadoop/logs
            df -h /var/hadoop/temp
            df -h /var/hadoop/data
            '
    done

```

```
---- ----
iris-gaia-blue-20220627-zeppelin
6.5M	/var/hadoop/logs/
20K	/var/hadoop/temp/
4.0K	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-master01
64M	/var/hadoop/logs/
144K	/var/hadoop/temp/
4.0K	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker01
1.1G	/var/hadoop/logs/
670M	/var/hadoop/temp/
409G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker02
675M	/var/hadoop/logs/
670M	/var/hadoop/temp/
451G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker03
1.7G	/var/hadoop/logs/
670M	/var/hadoop/temp/
359G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker04
572M	/var/hadoop/logs/
670M	/var/hadoop/temp/
506G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker05
995M	/var/hadoop/logs/
670M	/var/hadoop/temp/
797G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker06
654M	/var/hadoop/logs/
670M	/var/hadoop/temp/
332G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker07
322M	/var/hadoop/logs/
670M	/var/hadoop/temp/
218G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker08
763M	/var/hadoop/logs/
670M	/var/hadoop/temp/
398G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker09
967M	/var/hadoop/logs/
670M	/var/hadoop/temp/
374G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker10
655M	/var/hadoop/logs/
670M	/var/hadoop/temp/
493G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker11
1.2G	/var/hadoop/logs/
670M	/var/hadoop/temp/
319G	/var/hadoop/data/
---- ----
iris-gaia-blue-20220627-worker12
330M	/var/hadoop/logs/
670M	/var/hadoop/temp/
221G	/var/hadoop/data/
```

```
---- ----
iris-gaia-blue-20220627-zeppelin
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        374G   75M  355G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        374G   75M  355G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        374G   75M  355G   1% /mnt/local/vdb
---- ----
iris-gaia-blue-20220627-master01
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        14G  3.3G  9.9G  26% /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        14G  3.3G  9.9G  26% /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        14G  3.3G  9.9G  26% /
---- ----
iris-gaia-blue-20220627-worker01
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.8G  167G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.8G  167G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  411G  614G  41% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker02
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.4G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.4G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  453G  572G  45% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker03
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  2.4G  166G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  2.4G  166G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  360G  664G  36% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker04
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.3G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.3G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  508G  517G  50% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker05
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.7G  167G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.7G  167G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  799G  226G  78% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker06
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.4G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.4G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  333G  691G  33% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker07
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.1G  168G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.1G  168G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  219G  805G  22% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker08
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.5G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.5G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  399G  625G  39% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker09
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.7G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.7G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  375G  649G  37% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker10
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.4G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.4G  167G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  495G  530G  49% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker11
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.9G  167G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.9G  167G   2% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  321G  704G  32% /mnt/cinder/vdd
---- ----
iris-gaia-blue-20220627-worker12
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.1G  168G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb        178G  1.1G  168G   1% /mnt/local/vdb
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        1.0T  222G  802G  22% /mnt/cinder/vdd
```

**Comment by Zarquan** [comment]
Is this still an issue ?

**Comment by stvoutsin** [comment]
The issue is still there, and has to do with the Hadoop "data" directory reaching full capacity, leading to unhealthy worker nodes. The data directory is used for temporary data that gets written out to disk during Spark/Hadoop jobs which produce data that cannot fit into memory. 

One thing to look at is why/if this data should/needs to get cleared by some garbage collection process. 
Secondly, this is a known issue having to do with the fact that we can only get 180 Gb of local disk on each worker node with the existing Openstack flavours. 

A while ago I looked into using Ceph volumes for the data directory, but it looked like this was introducing some latency.
https://github.com/wfau/gaia-dmp/pull/829

However maybe its worth revisiting this to compare performance again. Also I can work on seeing how to replicate the issue on a test deploy

**Comment by NigelHambly** [comment]
I think your second point above is key. I suggest we do a targeted test:
- set up a clean test deploy
- execute one of the bigger examples (say the XP spectra trawl)
- examine the system for temp data while the interactive session is active (i.e. still logged in through the Zeppelin UI)
- see what happens when the user session is logged out

I would hope/expect any temp data created in such a scenario would get cleaned up. If it doesn't then that's the first thing to address.

**Comment by NigelHambly** [comment]
Note to self: running the similar spectra trawl (new Example 5) and checking worker user cache

`ssh worker01-06 du -h --summarize /var/hadoop/data/usercache/...`

from the master node I see up to 11GB of disk usage during execution that reduces to 4G once finished. IIUC this is consistent with the yarn config

`yarn.nodemanager.localizer.cache.cleanup.interval-ms=600000`
`yarn.nodemanager.localizer.cache.target-size-mb=10240`

which I believe means that anything above 10GB that is no longer in use will get scrubbed on a 10min timescale. Does this mean that up to 10GB can be left lying around on each worker I wonder? As a user, logging out from the Zeppelin UI does not affect this cached data, but I note that if I reset the pyspark interpreter via the cog icon in the UI, the data is cleared immediately.

**Comment by stvoutsin** [comment]
Should now be fixed in https://github.com/wfau/gaia-dmp/pull/1176
If we still have issues with disk overflow we can open a new one, with more recent/specific examples
