### ISSUE TITLE
Relocate HTTPS cron job to data node

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#839]
The current HTTPS deployment runs the renewal process using a cron job on the Zeppelin node.

If we have three deployments on red, green and blue clouds, all of them will have a cron job that will attempt to refresh the SSL certificate once a day. Only one of them will have the correct hostname be able to refresh the certificate.

When a Zeppelin node does update the certificate, there is no mechanism in place for transferring the new certificate to the data node ready for the next deployment to use.

Both of these can be solved by running the cron job on the data node rather than the Zeppelin node(s).

**Comment by stvoutsin** [comment]
Fixed in: https://github.com/wfau/gaia-dmp/pull/1215
