### ISSUE TITLE
Curating example notebooks

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#914]
The following tests were done with the eDR3 removed to look for things that referred to the eDR3 data rather than the DR3 data.

* Example 2. Data holdings
  * Description and links
    * Links point to documentation for eDR3
      * https://gea.esac.esa.int/archive/documentation/GEDR3/Gaia_archive/chap_datamodel/sec_dm_main_tables/ssec_dm_gaia_source.html
      * https://gea.esac.esa.int/archive/documentation/GEDR3/Gaia_archive/chap_datamodel/sec_dm_crossmatches/
      * https://gea.esac.esa.int/archive/documentation/GEDR3/Catalogue_consolidation/chap_crossmatch/
    * Gaia DR3 equivalents are
      *   https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_main_source_catalogue/ssec_dm_gaia_source.html
      * https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_cross-matches/
      * https://gea.esac.esa.int/archive/documentation/GDR3/Catalogue_consolidation/chap_crossmatch/
  * Column listing for a table
    * Query refers to tables in eDR3 rather than DR3
      *  `select * from gaiaedr3.gaia_source_ps1_best_neighbours`
    * Print satement  refers to eDR3 rather than DR3
      * `Column details of gaiaedr3.gaia_source_ps1_best_neighbours`
  * Querying with cross-matched data
    * Query refers to tables in eDR3 rather than DR3
      * `SELECT ... FROM gaiaedr3.gaia_source AS gaia INNER JOIN gaiaedr3.gaia_source_ps1_best_neighbours ...`

**Comment by Zarquan** [comment]
* Example 3. Source counts over the sky
  * All good

**Comment by Zarquan** [comment]
* Example 4. Mean proper motions over the sky
  * All good

**Comment by Zarquan** [comment]
* Example 5. Working with Gaia XP spectra
  * Sampling and plotting spectra
```
Fail to execute line 31: plot_spectra(sampled_spectrum, sampling = sampling, multi=False, show_plot=True, save_path=None, legend=True)
Traceback (most recent call last):
  File "/tmp/1658744544839-0/zeppelin_python.py", line 158, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 31, in <module>
TypeError: plot_spectra() got an unexpected keyword argument 'save_path'
```

**Comment by Zarquan** [comment]
* Example 6. Working with cross-matched surveys
  * Define a data aggregation
    * Query refers to tables in eDR3 rather than DR3 
      * `SELECT ... FROM gaiadr3.gaia_source AS g INNER JOIN gaiaedr3.gaia_source_tmasspsc_best_neighbours ...`
  * Visualise via matplotlib
    * This might be caused by empty result from querying missing eDR3 table (disabled for test) 
    * Check again when we put the eDR3 tables back in
```
/usr/local/lib64/python3.7/site-packages/scipy/sparse/sputils.py:114: UserWarning: object dtype is not supported by sparse matrices
  warnings.warn("object dtype is not supported by sparse matrices")
Fail to execute line 12: dense_data = sparse_data.todense()
Traceback (most recent call last):
  File "/tmp/1658744544839-0/zeppelin_python.py", line 153, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 12, in <module>
  File "/usr/local/lib64/python3.7/site-packages/scipy/sparse/base.py", line 864, in todense
    return asmatrix(self.toarray(order=order, out=out))
  File "/usr/local/lib64/python3.7/site-packages/scipy/sparse/coo.py", line 327, in toarray
    B.ravel('A'), fortran)
ValueError: unsupported data types in input
```

**Comment by Zarquan** [comment]
* Example 7. Good astrometric solutions via ML Random Forrest classifier
  * All good

**Comment by Zarquan** [comment]
The GaiaXPy error in example 5 is caused by a change to one of the parameter names from `save_path` to `output_path`.

**Comment by Zarquan** [comment]
* Create read-only versions of the public notebooks.
* Disable [edit on double click] for *all* notebooks.
* Update permissions on the examples to allow admin role to edit.
* Update role for our users (do we need to be both admin and user?)

**Comment by Zarquan** [comment]
Example 2. Data holdings 
* Updated the links to DR3 documentation
* Left the SQL queries pointing to eDR3 because the neighbour tables are not in DR3 yet (#909 ).

**Comment by Zarquan** [comment]
I think all of these issues have been addressed

**Comment by NigelHambly** [comment]
@Zarquan : regarding the occasional archaic spelling of "forrest" [sic] noted above is it OK if I rename notebook example 7. with the universally used modern spelling "... Random Forest classifier"

**Comment by Zarquan** [comment]
> @Zarquan : regarding the occasional archaic spelling of "forrest" [sic] noted above is it OK if I rename notebook example 7. with the universally used modern spelling "... Random Forest classifier"

Yep, no problem. The clone process iterates the notes in the folder, it doesn't refer to any one specific note by name.

**Comment by NigelHambly** [comment]
OK I've checked all the notebooks for the above and corrected and enhanced where necessary with a bunch of other features etc. I'm (re)closing the issue as dealt with.
