### ISSUE TITLE
Broken link for 2mass website

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#936]
Example 2. Data holdings has a broken link for 2mass
https://old.ipac.caltech.edu/2mass/releases/allsky/doc/sec2_2a.html

**Comment by Zarquan** [comment]
Example 6. Working with cross-matched surveys has the same broken link in the last cell.

**Comment by Zarquan** [comment]
I think this is because the IPAC site only provides an old version of SSL.
```
An error occurred during a connection to old.ipac.caltech.edu. Peer using unsupported version of security protocol.

Error code: SSL_ERROR_UNSUPPORTED_VERSION

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.

This web site might not support the TLS 1.2 protocol, which is the minimum version supported by Firefox.
```

**Comment by Zarquan** [comment]
Similar error using Chrome.
```
This site can’t provide a secure connection
old.ipac.caltech.edu uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by NigelHambly** [comment]
@Zarquan : could you check if the following link works for you in Chrome and Firefox (and any other browser for that matter):

https://irsa.ipac.caltech.edu/2MASS/download/allsky/format_psc.html

I think this a the more up-to-date website ... works fine in Safari on Mac.

**Comment by NigelHambly** [comment]
If I don't hear anything to the contrary by tomorrow I'll assume it's fine, commit to repo, and close this issue.

**Comment by Zarquan** [comment]
@NigelHambly Sorry, missed the comment yesterday - yes, the new link works fine :+1:

**Comment by NigelHambly** [comment]
Great thanks - relevant change is now committed to the notebook repo.
