### ISSUE TITLE
Broken link for HEALPixel tools

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#937]
Example 4. Mean proper motions over the sky has a broken link in the last cell.
https://lambda.gsfc.nasa.gov/toolbox/tb_pixelcoords.html

**Comment by NigelHambly** [comment]
The corrected link is https://lambda.gsfc.nasa.gov/toolbox/pixelcoords.html

Will be preserved with a bunch of other changes as part of global review of NBs and re-establishing the repo
