### ISSUE TITLE
Put example notebooks into source control

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#953]
The current deployment restores the examples from a backup of the whole notebook directory.
We need to have source control and history for the examples.

Plan is to have a master set of examples in source control that can be edited by the development team.
New user accounts are given a clone of the current state of the examples.

Initial step is to update the existing GitHib account with copies from the current live system and start using that as the master source for new accounts.

**Comment by Zarquan** [comment]
We need to document a process for updating the notebooks in source control without merge conflicts.
We also need to document a process for updating the copies that users already have if/when we find a critical change that needs to be deployed to all users.

**Comment by NigelHambly** [comment]
As discussed the main repo [here](https://github.com/wfau/aglais-notebooks) is now up-to-date with all changes from various places, and is where the notebooks should come from when there is a need to create new copies for new users. This constitutes a set of significant corrections and new features (especially in Example 5).

What to do about existing user's copies is not clear to me. Perhaps we should simply point them to the repo when there are significant new corrections and features like this (maybe tag a formal release in GitHub?) and say they are free to upload copies into their own folders (they then have the option to merge with any of their own changes, albeit in a rather inconvenient and manual way, importing the newly released notebooks with different names and comparing cells...).

**Comment by NigelHambly** [comment]
N.B. top level public examples folder should go.

**Comment by Zarquan** [comment]
Discussion at Gaia-DMp telecon:
* Delete the top level examples
* Use HEAD from [aglais-notebooks](https://github.com/wfau/aglais-notebooks) for new users
* Email existing users with link to new version of the examples

**Comment by Zarquan** [comment]
I think this is all done :+1:
