### ISSUE TITLE
Share stuck in "Extending" status

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#961]
Share:
URL: https://arcus.openstack.hpc.cam.ac.uk/project/shares/e4a87621-2e57-4a38-a7fb-283d0731572e/
ID: e4a87621-2e57-4a38-a7fb-283d0731572e

Share was created using the Arcus Opensatck UI:
(Click dropdown, "Extend share", set to 3072Gb)
Initially, the share was set to 1024Gb.

We are currently unable to mount & use or edit this share

**Comment by Zarquan** [comment]
Cambridge Jira ticket [HPCSSUP-47348](https://jira.hpc.cam.ac.uk/servicedesk/customer/portal/2/HPCSSUP-47348)

**Comment by Zarquan** [comment]
Reply from Paul Browne
> Finally got rid of this share, there were some inconsistencies in its owning share service host which when corrected unblocked that service host being able to delete the share.

**Comment by Zarquan** [comment]
The share had to be deleted in order to 'unstick' it, so will need to create a new data share for SVoutsinas.

**Comment by Zarquan** [comment]
User data share for SVoutsinas created automatically during latest deployment.
