### ISSUE TITLE
Restore example 4 from backup

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#977]
The notebook for example 4 has been modified, so we need to restore it from backup.

**Comment by Zarquan** [comment]
I think it was when we first invited external users to join and Steven Gough-Kelly was having trouble accessing his own notebooks. While I was trying to debug/fix the issue with his notebooks I said he could use the public ones to experiment with (it was either that or we loose one of our first customers). Looks like he did experiment with one of them, adding a few cells of his own at the end, including a write to a directory in his /user space.

We have backups from that day and a the day before earlier, it is just a case of finding the best one and replacing the copy on the live server. But due to the way that Zeppelin mangles everything it is probably going to be a real pain whichever way we choose to do it.

**Comment by Zarquan** [comment]
As yet we still don't have a plausible workable system for source control of the notebooks. Open to suggestions on how to handle it.
Needs to be able to cope with:
* Changes to user's notebooks on the live service
* Source control for changes to the example notebooks hosted on a separate service
* Clone example notebooks from source control to new user's accounts

**Comment by Zarquan** [comment]
If we are intending to remove the 'Public examples' folder, because everyone has their own copy of the notebooks, then we need to fix the copy in source control, and just delete the 'Public examples' folder on the live server.

**Comment by Zarquan** [comment]
Do we need to repair the clones in other user's copies of the examples ? We created several new users after Steven, and their copies of the examples were generated by cloning the 'Public examples' folder on the live server. So I'm guessing they all got a copy of Steven's edited example.
* If they haven't modified their own example, then we should replace their copy with a clean one.
* If they have modified their example, then we should leave it as-is.
* Do we tell them? I think that would be likely to cause more confusion than benefit.

**Comment by Zarquan** [comment]
Lots of side effects. We should probably plan what we intend to do and then review and discuss all the side effects and consequences before we go for it.

**Comment by NigelHambly** [comment]
Good grief. Well the good news is I have a pristine copy of all example NBs in DPAC SVN, so no worries on have a source for restoration. All the other musings above - let's discuss later this week.

**Comment by NigelHambly** [comment]
As part of a complete review of all notebooks I've restored example 4 to how it should be in the repo, so that part of this issue at least is addressed. 

How to handle propagating this (and the other enhancements/corrections) into existing user's copies is still an open question thought.

**Comment by NigelHambly** [comment]
Previously agreed that the GH master repo will be the source of all example copies for new users, while existing users will be pointed to new releases from there for notebook updates if they are interested.
