### ISSUE TITLE
Source control for notebooks

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#979]
As yet we still don't have a plausible workable system for source control of the notebooks. Open to suggestions on how to handle it. Needs to be able to cope with:

* Changes to user's notebooks on the live service
* Source control for changes to the example notebooks hosted on a separate service
* Clone example notebooks from source control to new user's accounts

**Comment by NigelHambly** [comment]
Let's try to keep duplication and proliferation of issues to a minimum; I suggest we continue this discussion in #953 where I've made a suggestion for a way forward.
