### ISSUE TITLE
Update AglaisBenchmarker to use updated JSON format from create-user tools 

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#982]
Recent changes to the crate-user tools have changed the  JSON format slightly. AglaisBenchmarker is expecting `.users[].shirouser.pass:` but the create-user tools are outputting `.users[].shirouser.password:`. 

Result is we need to use a `jq` script to re-format the output into a shape that AglaisBenchmarker can use.
```
    jq '
        {
        "users": [
                {
                "shirouser":
                    .users[] | .shirouser | {"name": .name, "pass": .password}
                }
            ]
        }
        ' /tmp/test-users.json \
    | tee /tmp/test-creds.json

```

**Comment by stvoutsin** [comment]
The benchmarker does use these user configurations now, so I'll close this one
