### ISSUE TITLE
Maintenance landing page

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#986]
We need a nice landing page to use when the site is down for maintenance.
* Enabled/disabled by a simple on/off switch
* Served by the Nginx proxy service as part of the normal deployment.
* Served by minimal deployment with just an Nginx service and this page.

**Comment by stvoutsin** [comment]
Is this sufficient for this issue ?
https://github.com/wfau/gaia-dmp/pull/1161
