### ISSUE TITLE
Matplotlib integration with Zeppelin and strange behaviour (no plots or too many plots)

### ISSUE THREAD

**Issue by NigelHambly** [wfau/gaia-dmp#990]
Just come across a weird one. Notebook example 5 (XP) makes a plot in cell 2 that should create 2 panels showing the blue and red arms of the XP spectrum for the example source specified. Fine as it stands.

I've noticed that if I execute Example 8, then try to repeat the above, I only get the blue panel. I think that's because example 8 reconfigures the system via the z.configure_mpl() builtin (e.g. see https://zeppelin.apache.org/docs/0.10.0/interpreter/python.html#matplotlib-integration) as follows:

z.configure_mpl(angular=True, close=False)

in order to render all plots in one results pane in Zeppelin. Furthermore, if I then try to explicitly reset this to the (presumed) default

z.configure_mpl(angular=False, close=False)

then run cell 2 from example 5, I get no fewer than 3 panels: the BP arm is plotted, then the RP, then a repeat of the BP arm!

It could be that I need to restart the python interpreter as all this reconfiguration jiggery-pokery has tied it in a knot, but on the live system atm I'm getting the intermittent "Error restart interpreter" pop-up so can't reset defaults that way.

@Zarquan : I'm wondering if this is what happened to you last week when testing things and getting no rendered results back from matplotlib: had you executed example 8 beforehand by any chance?!

I'm not sure how to reset the z.configure_mpl() in example 8... but I think I should. Ideas welcome!

**Comment by Zarquan** [comment]
@NigelHambly Yes, this looks familiar.
On the live system - in public example 5 the cell titled "First cell" has the following text `[<matplotlib.lines.Line2D object at 0x7efb6ee0b6d0>]` where we would expect to see a graph drawn
  
![Screenshot at 2022-08-29 16-21-42](https://user-images.githubusercontent.com/4954609/187236199-5afe049a-7da2-4ce8-b2de-38d95c5b6d9d.png)

**Comment by Zarquan** [comment]
@NigelHambly Bear in mind we are using an old version of Matplotlib.

The latest version is [3.5.2](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.5.2.html) and we are using [3.4.2](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.4.0.html).

There are a number of outstanding issues to update and test all of our components.
* #935 
* #473
* #695
* #920

**Comment by NigelHambly** [comment]
OK I've cracked it: I simply need to reset the configuration with the incantation

z.configure_mpl(angular = False, close = True)

after the relevant cells in Example Notebook 8. I will do so under the auspices of #953 etc.
