### ISSUE TITLE
User not able to restart interpreter

### ISSUE THREAD

**Issue by stvoutsin** [wfau/gaia-dmp#998]
**Description:**

Restarting interpreters fails for users in the current version deployed on live (2022-09-06)

Email from Dennis:
> 
> Hi,
> 
> I have noticed since the shift to the new system I am unable to restart the interpreter as before, is there a new way to do this for a user?
> 
> Using the previous method brings "Error restart interpreter.” and I do not have permission to view the interpreters page,
> 

I have been able to replicate this on a test deploy, and it seems like this is a permission error, as I see 401 errors in the Web console.

Update:

After looking into this a bit, it seems that the following line is to blame:
https://github.com/wfau/gaia-dmp/blob/master/deployments/hadoop-yarn/ansible/38-install-user-db.yml#L67

`/api/interpreter/** = authc, roles[admin]
`
Dennis & Nigel are create with the role: "user", which isn't included in the roles that have access to the interpreter endpoint, which is required for restarting an interpreter.

I have tried setting the line:

`/api/interpreter/** = authc, roles[user]
`
After this change the test users are able to restart their Spark interpreters.

**Comment by Zarquan** [comment]
Just to check, what the potential side effects of this are ?
Am I right in thinking that in our current configuration we create a separate interpreter for each user, for **all** of the interpreter types (pyspark, python, md etc).
So if we enable this, each user will be able to restart their interpreter, but it won't have any side effects for anyone else ?

**Comment by Zarquan** [comment]
Labelling this as high priority because it is impacting Dennis's work.

**Comment by stvoutsin** [comment]
Fixed in https://github.com/wfau/gaia-dmp/pull/1036
